apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
spec:
  selector:
    matchLabels:
      app: service2
  replicas: 1
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: service2
          image: service2
          imagePullPolicy: Never
          ports:
            - containerPort: 80
