apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: service3-destination
spec:
  host: service3-service
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 10
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 80
